---
# file: system/tasks/validation.yml
#
# validation tasks.
#

- name: ensure mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: "{{ item }} is not defined"
  with_items:
    - system_groups
    - system_ssh_deprecated_keys
    - system_users

- name: ensure system_groups elements have a name key
  fail:
    msg="group {{ item.key }} is missing a 'name' key"
  when: "{{ item.value.name is not defined }}"
  with_dict: "{{ system_groups }}"

- name: ensure system_users elements have a name key
  fail:
    msg="user {{ item.key }} is missing a 'name' key"
  when: "{{ item.value.name is not defined }}"
  with_dict: "{{ system_users }}"

- name: ensure system_users elements have a authorized key
  fail:
    msg="user {{ item.key }} is missing a 'authorized' key"
  when: "{{ item.value.authorized is not defined }}"
  with_dict: "{{ system_users }}"
